# Generated by Django 2.1.1 on 2018-12-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='片名')),
                ('poster', models.ImageField(upload_to='./imgs', verbose_name='海报')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='片名')),
                ('date', models.IntegerField(verbose_name='年代')),
                ('language', models.SmallIntegerField(choices=[(1, '汉语普通话'), (2, '英语'), (3, '日语'), (4, '韩语'), (5, '法语'), (6, '俄语'), (7, '西班牙语'), (8, '阿拉伯语'), (9, '其他语言')], default=1, verbose_name='语言')),
                ('captions', models.SmallIntegerField(choices=[(1, '中文字幕'), (2, '英文字幕')], default=1, verbose_name='字幕')),
                ('durations', models.SmallIntegerField(verbose_name='时长')),
                ('descriptions', models.CharField(max_length=512, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'LV1'), (2, 'LV2'), (3, 'LV3'), (4, 'LV4'), (5, 'LV5'), (6, 'LV6')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='actors',
            field=models.ManyToManyField(related_name='play', related_query_name='play', to='api.Person', verbose_name='演员'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='directors',
            field=models.ManyToManyField(related_name='direct', related_query_name='direct', to='api.Person', verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='screenwriter',
            field=models.ManyToManyField(related_name='writer', related_query_name='writer', to='api.Person', verbose_name='编剧'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MovieDetail'),
        ),
    ]
