# Generated by Django 2.1.1 on 2018-12-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_detail',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
