# Generated by Django 2.1.1 on 2018-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181231_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
