# Generated by Django 2.1.1 on 2018-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='片名')),
                ('date', models.IntegerField(verbose_name='年代')),
                ('location', models.CharField(max_length=32, verbose_name='国家/地区')),
                ('directors', models.CharField(max_length=128, verbose_name='导演')),
            ],
        ),
    ]
